### ISSUE TITLE
How it is possible in reverse, like graph to pandas?

### ISSUE THREAD

**Issue by umairq** [cadmiumkitty/rdfpandas#2]
Hi
I have been able to convert dataframe to graph but I also want the reverse of it.
Is it possible? how?

thanks

**Comment by cadmiumkitty** [comment]
Hi Umair, It is not possible with rdfpandas yet, but https://github.com/paulhoule/gastrodon have support for something similar (I don't think you can go straight from RDF in, say, Turtle to Pandas DataFrame, but you can go from SPARQL query to DataFrame). Here's my example: https://github.com/cadmiumkitty/rdf-jupyter/blob/master/work/rdf-roundtrip-example.ipynb

**Comment by umairq** [comment]
Thanks Eugene for prompt reply

**Comment by pebbie** [comment]
assuming a simple graph shape, i can achieve the reverse by using this [gist](https://gist.github.com/pebbie/a3c9795a20510f2765c3d707eaff4e5d)

is this acceptable for a PR?

**Comment by cadmiumkitty** [comment]
Thanks, Peb, I was thinking something similar but more generic, not relying on there being a specific shape, so that the roundtrip works (would need a test too, etc). If you have that, then PR is welcome. Alternatively, I can try and put it together in the next week or two, judging from the traffic here.

**Comment by cadmiumkitty** [comment]
Hi All, Version 1.0.0 that supports RDF to DataFrame among other things is out, see https://rdfpandas.readthedocs.io/en/1.0.0/ for usage.
